services:
  db: 
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sales-db
      POSTGRES_PASSWORD: 123456
    volumes:
      - "pgdata:/var/lib/postgresql/data"
volumes:
  pgdata: