Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.network "forwarded_port", guest: 5432, host: 5432, host_ip: "127.0.0.1"
#   config.vm.network "private_network", ip: "192.168.56.2
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", path: "provision.sh"
end
